Python Assignment: Data Structures, Functions, Numpy & Pandas



Instructions
• Attempt all questions.
• Submit the completed assignment in .ipynb format.
• Use appropriate function definitions and comments for clarity.
                                                   


                              ### Assignment Questions

### Section A: Data Structures & Control Structures

In [1]:
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# append
numbers.append(60)
print("After append:", numbers)

# extend
numbers.extend([70, 80])
print("After extend:", numbers)

# insert
numbers.insert(2, 25)
print("After insert:", numbers)

# remove
numbers.remove(25)
print("After remove:", numbers)

# pop
numbers.pop()
print("After pop:", numbers)

# index
print("Index of 30:", numbers.index(30))

# count
numbers.append(20)
print("Count of 20:", numbers.count(20))

# sort
numbers.sort()
print("Sorted List:", numbers)

# reverse
numbers.reverse()
print("Reversed List:", numbers)

# clear
numbers.clear()
print("After clear:", numbers)

Original List: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 30, 40, 50, 60, 70, 80]
After pop: [10, 20, 30, 40, 50, 60, 70]
Index of 30: 2
Count of 20: 2
Sorted List: [10, 20, 20, 30, 40, 50, 60, 70]
Reversed List: [70, 60, 50, 40, 30, 20, 20, 10]
After clear: []


In [3]:
# Create a tuple with 3 student names
students = ("Ali", "Rahul", "Aman")

print("Original Tuple:", students)

# Trying to change second name
students[1] = "Ravi"

Original Tuple: ('Ali', 'Rahul', 'Aman')


TypeError: 'tuple' object does not support item assignment

In [4]:
# Create a set with duplicate values
numbers_set = {1, 2, 3, 4, 4, 5, 5, 6}

print("Set Output:", numbers_set)

Set Output: {1, 2, 3, 4, 5, 6}


In [5]:
# Create dictionary
person = {
    "name": "Aftab",
    "age": 22,
    "city": "Bangalore"
}

# Update age
person["age"] = 23

# Add new key
person["email"] = "aftab@example.com"

print("Final Dictionary:", person)

Final Dictionary: {'name': 'Aftab', 'age': 23, 'city': 'Bangalore', 'email': 'aftab@example.com'}


In [6]:
age = 20

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [7]:
marks = 82

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Fail")

Grade: B


In [8]:
num = 10

if num > 0:
    print("Number is Positive")
    
    if num % 2 == 0:
        print("Number is Even")
    else:
        print("Number is Odd")

elif num == 0:
    print("Number is Zero")

else:
    print("Number is Negative")

Number is Positive
Number is Even


###Section B: NumPy

###Section B: NumPy

###Section B: NumPy

In [9]:
import numpy as np
import pandas as pd

# Scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# 2D array
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])

print("2D Array:\n", array_2d)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [10]:
random_array = np.random.randint(0, 100, (4,4))

print("Random 4x4 Array:\n", random_array)

Random 4x4 Array:
 [[22 14 87 13]
 [ 6 50  9 17]
 [74 64 78 33]
 [27 77  0 41]]


In [11]:
# Create 3x3 numpy array
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

# Convert to DataFrame
df = pd.DataFrame(array, columns=['A', 'B', 'C'])

print("Pandas DataFrame:\n")
print(df)

Pandas DataFrame:

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
